import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  diffCatalogs,
  type ModelCatalog,
  type OptionDefinition,
} from "../packages/core/src/index.ts";
import { openRouterAdapter, vercelGatewayAdapter } from "../packages/providers/src/index.ts";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const shouldWrite = process.argv.includes("--write");
const adapters = [vercelGatewayAdapter, openRouterAdapter] as const;
let hasDrift = false;

for (const adapter of adapters) {
  const catalog = materialCatalog(await adapter.discover());
  const path = resolve(root, "catalog", "snapshots", `${adapter.id}.json`);
  if (shouldWrite) {
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, `${JSON.stringify(catalog, omitRaw, 2)}\n`, "utf8");
    console.log(`Updated ${adapter.id}: ${catalog.models.length} models`);
    continue;
  }

  let previous: ModelCatalog;
  try {
    previous = JSON.parse(await readFile(path, "utf8")) as ModelCatalog;
  } catch (error) {
    console.error(`Missing or invalid ${adapter.id} snapshot. Run pnpm catalog:refresh.`);
    console.error(error instanceof Error ? error.message : String(error));
    hasDrift = true;
    continue;
  }
  const drift = diffCatalogs(previous, catalog);
  if (!drift.hasChanges) {
    console.log(`Current ${adapter.id}: ${catalog.models.length} models`);
    continue;
  }
  hasDrift = true;
  console.error(
    `${adapter.id} drift: +${drift.added.length} -${drift.removed.length} ~${drift.changed.length}`,
  );
  for (const model of drift.added.slice(0, 20)) {
    console.error(`  added: ${model.key}`);
  }
  for (const model of drift.removed.slice(0, 20)) {
    console.error(`  removed: ${model.key}`);
  }
  for (const change of drift.changed.slice(0, 20)) {
    console.error(`  ${change.key}: ${change.fields.join(", ")}`);
  }
}

const generatedPath = resolve(root, "packages", "providers", "src", "generated", "modelIds.ts");
const generatedSource = await generateModelIdSource();
if (shouldWrite) {
  await mkdir(dirname(generatedPath), { recursive: true });
  await writeFile(generatedPath, generatedSource, "utf8");
  console.log("Updated generated gateway model ID types");
} else {
  const currentGenerated = await readFile(generatedPath, "utf8").catch(() => "");
  if (currentGenerated !== generatedSource) {
    console.error("Generated model ID types are stale. Run pnpm catalog:refresh.");
    hasDrift = true;
  }
}

if (hasDrift) {
  process.exitCode = 1;
}

async function generateModelIdSource(): Promise<string> {
  const snapshots = await Promise.all(
    adapters.map(async (adapter) => {
      const path = resolve(root, "catalog", "snapshots", `${adapter.id}.json`);
      const catalog = JSON.parse(await readFile(path, "utf8")) as ModelCatalog;
      return [adapter.id, catalog] as const;
    }),
  );
  const declarations = snapshots
    .map(([provider, catalog]) => {
      const pascal = provider === "openrouter" ? "OpenRouter" : "Vercel";
      const modelIds = catalog.models.map((model) => model.id).sort();
      return `/** Model IDs in the reviewed ${provider} snapshot. */\nexport const known${pascal}ModelIds = ${JSON.stringify(modelIds, null, 2)} as const;\n\n/** A model ID known when this package was generated. */\nexport type Known${pascal}ModelId = (typeof known${pascal}ModelIds)[number];`;
    })
    .join("\n\n");
  const optionsByKey = snapshots
    .flatMap(([, catalog]) => catalog.models)
    .sort((left, right) => left.key.localeCompare(right.key))
    .map((model) => `  readonly ${JSON.stringify(model.key)}: ${optionObjectType(model.options)};`)
    .join("\n");
  return `// Generated by pnpm catalog:refresh. Do not edit by hand.\n\n${declarations}\n\n/** A gateway model ID known when this package was generated. */\nexport type KnownGatewayModelId = KnownVercelModelId | KnownOpenRouterModelId;\n\n/** Exact selectable option values in the reviewed gateway snapshots. */\nexport interface KnownGatewayOptionValuesByKey {\n${optionsByKey}\n}\n\n/** A provider-qualified gateway model key known when this package was generated. */\nexport type KnownGatewayModelKey = keyof KnownGatewayOptionValuesByKey;\n\n/** Exact option values for one reviewed gateway model. */\nexport type KnownGatewayOptionValues<TKey extends KnownGatewayModelKey> = KnownGatewayOptionValuesByKey[TKey];\n`;
}

function optionObjectType(options: readonly OptionDefinition[]): string {
  const supported = options.filter((option) => option.support.status === "supported");
  if (supported.length === 0) {
    return "Readonly<{ readonly [key: string]: never }>";
  }
  const fields = supported
    .map((option) => `readonly ${JSON.stringify(option.key)}?: ${optionValueType(option)}`)
    .join("; ");
  return `Readonly<{ ${fields} }>`;
}

function optionValueType(option: OptionDefinition): string {
  switch (option.kind) {
    case "boolean":
      return "boolean";
    case "enum":
      return option.values.map((value) => JSON.stringify(value)).join(" | ") || "never";
    case "integer":
    case "number":
      return "number";
    case "string-list":
      return "readonly string[]";
  }
}

function omitRaw(key: string, value: unknown): unknown {
  return key === "raw" ? undefined : value;
}

function materialCatalog(catalog: ModelCatalog): ModelCatalog {
  return {
    ...catalog,
    models: catalog.models.map((model) => ({
      ...model,
      sources: [],
      raw: undefined,
      ...(model.contextWindow === undefined
        ? {}
        : { contextWindow: { ...model.contextWindow, sources: [] } }),
      ...(model.maxOutputTokens === undefined
        ? {}
        : { maxOutputTokens: { ...model.maxOutputTokens, sources: [] } }),
      capabilities: {
        input: stripCapabilityMap(model.capabilities.input),
        output: stripCapabilityMap(model.capabilities.output),
        reasoning: { ...model.capabilities.reasoning, evidence: [] },
        tools: { ...model.capabilities.tools, evidence: [] },
        structuredOutput: { ...model.capabilities.structuredOutput, evidence: [] },
        promptCaching: { ...model.capabilities.promptCaching, evidence: [] },
      },
      prices: model.prices.map((price) => ({ ...price, evidence: [] })),
      routes: model.routes.map((route) => ({
        ...route,
        sources: [],
        raw: undefined,
        prices: route.prices.map((price) => ({ ...price, evidence: [] })),
      })),
      options: model.options.map((option) => ({
        ...option,
        support: { ...option.support, evidence: [] },
      })),
      requirements: model.requirements.map((requirement) => ({
        ...requirement,
        sources: [],
        support: { ...requirement.support, evidence: [] },
      })),
    })),
  };
}

function stripCapabilityMap(
  values: Readonly<
    Record<
      string,
      { readonly status: string; readonly evidence: readonly unknown[]; readonly note?: string }
    >
  >,
): Readonly<
  Record<
    string,
    { readonly status: string; readonly evidence: readonly unknown[]; readonly note?: string }
  >
> {
  return Object.fromEntries(
    Object.entries(values).map(([key, value]) => [key, { ...value, evidence: [] }]),
  );
}
