import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const packageRoot = resolve(root, "node_modules", "@lobehub", "icons-static-svg", "icons");
const outputPath = resolve(root, "packages", "elements", "src", "generated", "brandIcons.ts");
const slugs = [
  "aionlabs",
  "alibaba",
  "anthropic",
  "arcee",
  "baidu",
  "bedrock",
  "bfl",
  "bytedance",
  "claude",
  "cohere",
  "deepseek",
  "fishaudio",
  "gemini",
  "gemma",
  "google",
  "grok",
  "ibm",
  "inception",
  "kimi",
  "kling",
  "kwaipilot",
  "liquid",
  "meta",
  "microsoft",
  "minimax",
  "mistral",
  "moonshot",
  "morph",
  "nousresearch",
  "nova",
  "nvidia",
  "openai",
  "openrouter",
  "perplexity",
  "poolside",
  "qwen",
  "recraft",
  "relace",
  "stepfun",
  "tencent",
  "upstage",
  "vercel",
  "voyage",
  "xai",
  "xiaomimimo",
  "zai",
] as const;

const entries = await Promise.all(
  slugs.map(async (slug) => {
    const source = await readFile(resolve(packageRoot, `${slug}.svg`), "utf8");
    const svg = source
      .replace(/<title>.*?<\/title>/u, "")
      .replace(
        /<svg[^>]*>/u,
        '<svg viewBox="0 0 24 24" fill="currentColor" fill-rule="evenodd" aria-hidden="true" focusable="false">',
      )
      .trim();
    return [slug, svg] as const;
  }),
);
const generated = `// Generated by pnpm icons:refresh from @lobehub/icons-static-svg. Do not edit by hand.\n\n/** Reviewed AI brand SVGs bundled without a runtime icon dependency. */\n// oxfmt-ignore\nexport const brandIcons: Readonly<Record<string, string>> = ${JSON.stringify(Object.fromEntries(entries), null, 2)};\n`;

if (process.argv.includes("--write")) {
  await mkdir(resolve(outputPath, ".."), { recursive: true });
  await writeFile(outputPath, generated, "utf8");
  console.log(`Updated ${slugs.length} bundled brand icons`);
} else {
  const current = await readFile(outputPath, "utf8").catch(() => "");
  if (current !== generated) {
    console.error("Bundled brand icons are stale. Run pnpm icons:refresh.");
    process.exitCode = 1;
  } else {
    console.log(`Current bundled brand icons: ${slugs.length}`);
  }
}
